In [3]:
import pandas as pd

df = pd.read_csv("../data/IPL.csv")

print(df.shape)

C:\Users\routc\AppData\Local\Temp\ipykernel_12160\3155497718.py:3: DtypeWarning: Columns (28,29,30,31,43,46,47,48,51) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../data/IPL.csv")

(283678, 65)

In [5]:
df.head()

,Unnamed: 0,match_id,date,match_type,event_name,innings,batting_team,bowling_team,over,ball,...,team_balls,team_wicket,new_batter,power_surge_start,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out
0,141607,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,...,1,0,NaN,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
1,141608,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,...,2,0,NaN,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
2,141609,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,...,2,0,NaN,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
3,141610,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,...,3,0,NaN,NaN,0,2,0,"('BB McCullum', 'SC Ganguly')",NaN,False
4,141611,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,...,4,0,NaN,NaN,0,3,0,"('BB McCullum', 'SC Ganguly')",NaN,False

In [7]:
df.columns.tolist()

['Unnamed: 0',
 'match_id',
 'date',
 'match_type',
 'event_name',
 'innings',
 'batting_team',
 'bowling_team',
 'over',
 'ball',
 'ball_no',
 'batter',
 'bat_pos',
 'runs_batter',
 'balls_faced',
 'bowler',
 'valid_ball',
 'runs_extras',
 'runs_total',
 'runs_bowler',
 'runs_not_boundary',
 'extra_type',
 'non_striker',
 'non_striker_pos',
 'wicket_kind',
 'player_out',
 'fielders',
 'runs_target',
 'review_batter',
 'team_reviewed',
 'review_decision',
 'umpire',
 'umpires_call',
 'player_of_match',
 'match_won_by',
 'win_outcome',
 'toss_winner',
 'toss_decision',
 'venue',
 'city',
 'day',
 'month',
 'year',
 'season',
 'gender',
 'team_type',
 'superover_winner',
 'result_type',
 'method',
 'balls_per_over',
 'overs',
 'event_match_no',
 'stage',
 'match_number',
 'team_runs',
 'team_balls',
 'team_wicket',
 'new_batter',
 'power_surge_start',
 'batter_runs',
 'batter_balls',
 'bowler_wicket',
 'batting_partners',
 'next_batter',
 'striker_out']

In [9]:
df[['match_id',
    'batting_team',
    'bowling_team',
    'over',
    'ball',
    'runs_total']].head(10)

,match_id,batting_team,bowling_team,over,ball,runs_total
0,335982,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,1
1,335982,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,0
2,335982,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,1
3,335982,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,0
4,335982,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,0
5,335982,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,0
6,335982,Kolkata Knight Riders,Royal Challengers Bangalore,0,6,1
7,335982,Kolkata Knight Riders,Royal Challengers Bangalore,1,1,0
8,335982,Kolkata Knight Riders,Royal Challengers Bangalore,1,2,4
9,335982,Kolkata Knight Riders,Royal Challengers Bangalore,1,3,4

In [11]:
print(df.shape)

(283678, 65)

In [13]:
print(df['match_id'].nunique())

1193

In [15]:
df[['match_id','batting_team','bowling_team']].drop_duplicates().head(10)

      match_id                 batting_team                 bowling_team
0       335982        Kolkata Knight Riders  Royal Challengers Bangalore
124     335982  Royal Challengers Bangalore        Kolkata Knight Riders
225     335983          Chennai Super Kings              Kings XI Punjab
349     335983              Kings XI Punjab          Chennai Super Kings
473     335984             Rajasthan Royals             Delhi Daredevils
595     335984             Delhi Daredevils             Rajasthan Royals
692     335985               Mumbai Indians  Royal Challengers Bangalore
815     335985  Royal Challengers Bangalore               Mumbai Indians
938     335986              Deccan Chargers        Kolkata Knight Riders
1056    335986        Kolkata Knight Riders              Deccan Chargers

In [17]:
df.columns.tolist()

['Unnamed: 0',
 'match_id',
 'date',
 'match_type',
 'event_name',
 'innings',
 'batting_team',
 'bowling_team',
 'over',
 'ball',
 'ball_no',
 'batter',
 'bat_pos',
 'runs_batter',
 'balls_faced',
 'bowler',
 'valid_ball',
 'runs_extras',
 'runs_total',
 'runs_bowler',
 'runs_not_boundary',
 'extra_type',
 'non_striker',
 'non_striker_pos',
 'wicket_kind',
 'player_out',
 'fielders',
 'runs_target',
 'review_batter',
 'team_reviewed',
 'review_decision',
 'umpire',
 'umpires_call',
 'player_of_match',
 'match_won_by',
 'win_outcome',
 'toss_winner',
 'toss_decision',
 'venue',
 'city',
 'day',
 'month',
 'year',
 'season',
 'gender',
 'team_type',
 'superover_winner',
 'result_type',
 'method',
 'balls_per_over',
 'overs',
 'event_match_no',
 'stage',
 'match_number',
 'team_runs',
 'team_balls',
 'team_wicket',
 'new_batter',
 'power_surge_start',
 'batter_runs',
 'batter_balls',
 'bowler_wicket',
 'batting_partners',
 'next_batter',
 'striker_out']