In [13]:
import pandas as pd
df = pd.read_csv("../data/IPL.csv")
print(df.shape)

C:\Users\routc\AppData\Local\Temp\ipykernel_15140\3452686239.py:2: DtypeWarning: Columns (28,29,30,31,43,46,47,48,51) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../data/IPL.csv")

(283678, 65)

In [11]:
required_columns = [
    'match_id',
    'date',
    'innings',
    'batting_team',
    'bowling_team',
    'over',
    'ball',
    'batter',
    'bowler',
    'runs_total',
    'wicket_kind',
    'player_out',
    'venue',
    'season'
]
ipl_data = df[required_columns]
ipl_data.head()

,match_id,date,innings,batting_team,bowling_team,over,ball,batter,bowler,runs_total,wicket_kind,player_out,venue,season
0,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,1,NaN,NaN,M Chinnaswamy Stadium,2007/08
1,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,0,NaN,NaN,M Chinnaswamy Stadium,2007/08
2,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,1,NaN,NaN,M Chinnaswamy Stadium,2007/08
3,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,0,NaN,NaN,M Chinnaswamy Stadium,2007/08
4,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,0,NaN,NaN,M Chinnaswamy Stadium,2007/08

In [5]:
print(ipl_data.shape)

(283678, 14)

In [9]:
ipl_data.to_csv("../data/ipl_clean.csv", index=False)
print("File Saved")

File Saved

In [15]:
import pandas as pd
df = pd.read_csv("../data/IPL.csv")
# Remove unwanted index column
df = df.drop(columns=["Unnamed: 0"])
print(df.shape)

C:\Users\routc\AppData\Local\Temp\ipykernel_15140\3443317266.py:3: DtypeWarning: Columns (28,29,30,31,43,46,47,48,51) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../data/IPL.csv")

(283678, 64)

In [17]:
df.to_csv("../data/IPL_snowflake.csv", index=False)
print("New file created")

New file created

In [19]:
print(df.columns.tolist())

['match_id', 'date', 'match_type', 'event_name', 'innings', 'batting_team', 'bowling_team', 'over', 'ball', 'ball_no', 'batter', 'bat_pos', 'runs_batter', 'balls_faced', 'bowler', 'valid_ball', 'runs_extras', 'runs_total', 'runs_bowler', 'runs_not_boundary', 'extra_type', 'non_striker', 'non_striker_pos', 'wicket_kind', 'player_out', 'fielders', 'runs_target', 'review_batter', 'team_reviewed', 'review_decision', 'umpire', 'umpires_call', 'player_of_match', 'match_won_by', 'win_outcome', 'toss_winner', 'toss_decision', 'venue', 'city', 'day', 'month', 'year', 'season', 'gender', 'team_type', 'superover_winner', 'result_type', 'method', 'balls_per_over', 'overs', 'event_match_no', 'stage', 'match_number', 'team_runs', 'team_balls', 'team_wicket', 'new_batter', 'power_surge_start', 'batter_runs', 'batter_balls', 'bowler_wicket', 'batting_partners', 'next_batter', 'striker_out']

In [21]:
import pandas as pd
df = pd.read_csv("../data/IPL_snowflake.csv")
df['event_match_no'].unique()[:20]

C:\Users\routc\AppData\Local\Temp\ipykernel_15140\523800161.py:2: DtypeWarning: Columns (27,28,29,30,42,45,46,47,50) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../data/IPL_snowflake.csv")

array([1, 2, 3, 5, 4, 6, 7, 8, 9, 10, 12, 11, 14, 13, 15, 16, 17, 19, 18,
       20], dtype=object)

In [23]:
df[df['event_match_no'] == 'Unknown'][['event_match_no']].head()

      event_match_no
12801        Unknown
12802        Unknown
12803        Unknown
12804        Unknown
12805        Unknown

In [25]:
print(df['event_match_no'].dtype)

object

In [27]:
df['event_match_no'] = pd.to_numeric(
    df['event_match_no'],
    errors='coerce'
)

In [29]:
df.to_csv("../data/IPL_fixed.csv", index=False)
print("Saved")

Saved

In [31]:
for col in df.columns:
    try:
        pd.to_numeric(df[col])
    except:
        pass

In [33]:
df['event_match_no'].unique()[:20]

array([ 1.,  2.,  3.,  5.,  4.,  6.,  7.,  8.,  9., 10., 12., 11., 14.,
       13., 15., 16., 17., 19., 18., 20.])

In [35]:
print(df['event_match_no'].dtype)

float64

In [37]:
df[df['event_match_no'].isna()].shape

(16713, 64)

In [39]:
df['event_match_no'].unique()[-20:]

array([55., 56., nan, 47., 57., 58., 59., 60., 61., 62., 63., 64., 65.,
       66., 67., 68., 69., 70., 71., 72.])

In [41]:
df['event_match_no'].value_counts(dropna=False).head(20)

event_match_no
NaN     16713
16.0     4687
9.0      4637
23.0     4617
15.0     4615
4.0      4612
21.0     4610
24.0     4604
10.0     4601
11.0     4597
5.0      4593
17.0     4568
19.0     4565
18.0     4538
8.0      4517
1.0      4513
22.0     4507
20.0     4485
2.0      4467
30.0     4463
Name: count, dtype: int64

In [43]:
df.iloc[12802]

match_id                                 336038
date                                 2008-05-30
match_type                                  T20
event_name                Indian Premier League
innings                                       1
                               ...
batter_balls                                  1
bowler_wicket                                 0
batting_partners    ('GC Smith', 'SA Asnodkar')
next_batter                                 NaN
striker_out                               False
Name: 12802, Length: 64, dtype: object

In [45]:
print(df.loc[12802, 'event_match_no'])

nan

In [47]:
print(df['event_match_no'].dtype)

print(df['event_match_no'].isna().sum())

float64
16713

In [49]:
import pandas as pd

df = pd.read_csv("../data/IPL_snowflake.csv")

bad_rows = df[
    pd.to_numeric(df['event_match_no'], errors='coerce').isna()
]

print("Bad rows:", len(bad_rows))

bad_rows[['event_match_no']].drop_duplicates().head(20)

C:\Users\routc\AppData\Local\Temp\ipykernel_15140\1367242435.py:3: DtypeWarning: Columns (27,28,29,30,42,45,46,47,50) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../data/IPL_snowflake.csv")

Bad rows: 16713

      event_match_no
12801        Unknown

In [51]:
df['event_match_no'] = df['event_match_no'].astype(str)

print(df['event_match_no'].dtype)

object

In [53]:
df.to_csv("../data/IPL_fixed.csv", index=False)

print("IPL_fixed.csv created")

IPL_fixed.csv created

In [58]:
import snowflake.connector

print("Snowflake Connector Installed")

Snowflake Connector Installed

In [59]:
pip install snowflake-connector-python

Requirement already satisfied: snowflake-connector-python in c:\users\routc\anaconda3\lib\site-packages (4.6.0)
Requirement already satisfied: asn1crypto<2.0.0,>0.24.0 in c:\users\routc\anaconda3\lib\site-packages (from snowflake-connector-python) (1.5.1)
Requirement already satisfied: cryptography>=46.0.5 in c:\users\routc\anaconda3\lib\site-packages (from snowflake-connector-python) (49.0.0)
Requirement already satisfied: pyOpenSSL>=24.0.0 in c:\users\routc\anaconda3\lib\site-packages (from snowflake-connector-python) (26.3.0)
Requirement already satisfied: pyjwt<3.0.0,>=2.10.1 in c:\users\routc\anaconda3\lib\site-packages (from snowflake-connector-python) (2.13.0)
Requirement already satisfied: pytz in c:\users\routc\anaconda3\lib\site-packages (from snowflake-connector-python) (2024.1)
Requirement already satisfied: requests<3.0.0,>=2.32.4 in c:\users\routc\anaconda3\lib\site-packages (from snowflake-connector-python) (2.34.2)
Requirement already satisfied: packaging in c:\users\routc\anaconda3\lib\site-packages (from snowflake-connector-python) (24.1)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\routc\anaconda3\lib\site-packages (from snowflake-connector-python) (3.3.2)
Requirement already satisfied: idna<4,>=3.7 in c:\users\routc\anaconda3\lib\site-packages (from snowflake-connector-python) (3.7)
Requirement already satisfied: certifi>=2024.7.4 in c:\users\routc\anaconda3\lib\site-packages (from snowflake-connector-python) (2024.8.30)
Requirement already satisfied: typing_extensions<5,>=4.3 in c:\users\routc\anaconda3\lib\site-packages (from snowflake-connector-python) (4.11.0)
Requirement already satisfied: filelock<4,>=3.5 in c:\users\routc\anaconda3\lib\site-packages (from snowflake-connector-python) (3.13.1)
Requirement already satisfied: sortedcontainers>=2.4.0 in c:\users\routc\anaconda3\lib\site-packages (from snowflake-connector-python) (2.4.0)
Requirement already satisfied: platformdirs<5.0.0,>=2.6.0 in c:\users\routc\anaconda3\lib\site-packages (from snowflake-connector-python) (3.10.0)
Requirement already satisfied: tomlkit in c:\users\routc\anaconda3\lib\site-packages (from snowflake-connector-python) (0.11.1)
Requirement already satisfied: boto3>=1.24 in c:\users\routc\anaconda3\lib\site-packages (from snowflake-connector-python) (1.43.34)
Requirement already satisfied: botocore>=1.24 in c:\users\routc\anaconda3\lib\site-packages (from snowflake-connector-python) (1.43.34)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in c:\users\routc\anaconda3\lib\site-packages (from boto3>=1.24->snowflake-connector-python) (1.0.1)
Requirement already satisfied: s3transfer<0.20.0,>=0.19.0 in c:\users\routc\anaconda3\lib\site-packages (from boto3>=1.24->snowflake-connector-python) (0.19.0)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in c:\users\routc\anaconda3\lib\site-packages (from botocore>=1.24->snowflake-connector-python) (2.9.0.post0)
Requirement already satisfied: urllib3!=2.2.0,<3,>=1.25.4 in c:\users\routc\anaconda3\lib\site-packages (from botocore>=1.24->snowflake-connector-python) (2.2.3)
Requirement already satisfied: cffi>=2.0.0 in c:\users\routc\anaconda3\lib\site-packages (from cryptography>=46.0.5->snowflake-connector-python) (2.0.0)
Requirement already satisfied: pycparser in c:\users\routc\anaconda3\lib\site-packages (from cffi>=2.0.0->cryptography>=46.0.5->snowflake-connector-python) (2.21)
Requirement already satisfied: six>=1.5 in c:\users\routc\anaconda3\lib\site-packages (from python-dateutil<3.0.0,>=2.1->botocore>=1.24->snowflake-connector-python) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution ~yspark (C:\Users\routc\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~yspark (C:\Users\routc\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~yspark (C:\Users\routc\anaconda3\Lib\site-packages)